server:
  port: 8888
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accept-count: 100
    threads:
      max: 400
      min-spare: 50

spring:
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/onlinecinema?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    dbcp2:
      initial-size: 5
      min-idle: 10
      max-total: 10
      max-wait-millis: 60000
  thymeleaf:
    enabled: true
    mode: HTML
    encoding: UTF-8
    cache: false
  redis:
    database: 0
    host: 172.30.169.123
    port: 6379
    password:
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 20
        max-wait: -1ms
        max-idle: 10
        min-idle: 5
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  session:
    store-type: redis

mybatis-plus:
  type-aliases-package: com.liuyetech.onlinecinemamanager.domain
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

sa-token:
  token-name: onlinecinema
  timeout: 3600
  activity-timeout: -1
  is-concurrent: false
  is-share: false
  token-style: random-64
  is-log: false
  auto-renew: false

ali-pay:
  app-id: 2021000122610452
  merchant-private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDIS297F/qq5sQrkjvSOeT64vcJ5o29+orV39UB7ZCsCpxJEnSDzTLgTVD2CUXSNdfAiOLc1UIVsWkiLHmMYqK8ixcV+r6bXLYVSk+9C1LVp9SCqVUhiaxr1Gzm8iHIdTkTpOgyTT9WCLNrWbH77TPtO38ht4w4/nSFSe6yNYmCMy9x3Suu8QPwZbNdPfZ2YGds9KPhqY9F+2SGkAa7LrSwz2mMcBs4zOY5ZnW4Jk8O8ZVIBc47Wc/Ml5pOBnuP1s81fbxVZ9FEGRg05QJvMJEj2fqqk8tk7af+JgMfr/bjK+bX2+3uHrcNQytNVrLfI3fWP5VypS3EeVUaPumzfaZJAgMBAAECggEADXmNuXFGiuLVhbzjy2PbtMk6J29cT9CgMH1LfkK2PezE0OGt9wQCDTcGYFcFXHwE1M4gvQyX0o/J6+OkFb65BggxeGgTFK6rDUmfja9KVldhI50yvfveHq7+2JankS3Ztimc+W1a+nXBZFJ3d+RgXvBmwCTyCQ+NVT5BEboqUxjx8kxFGaNP/QY7MSuFjouj8ZQvBYadeZsl9nF0mYTafM7H67ly5SpKQ6NTQ/oCV7/m7Ky3NoZ0uASR8Abbk/7/VgxAyf0xY8Vdoj7/MpE2iVcrNHCMxvfgezTGs0c8cLZEsZJqIj9pR5z6rDr2/0AeWA3QpBqgRUtSwEZwitvykQKBgQDtnrRUwNxuNALXIrbigwKOwcRuUl2GuuZbKEwHrvyL/LIzVj5JBCd9/UYYAHCaA6UDqjTUEPhc4Uz6JgEZPJgBkgIjg8uIdkTDNLk+2zI+aScQi9Tij3r/YMNK1yjDkz3A15CSQL66IMl9Gj+zTG5/DJRVtJn2dCXHKUN3IltJ3QKBgQDXyZ/nXgCETCM16amVT6zmW93mJXgaafM1+/+nUNuz5n9LyCTHbac9gS/uvdk5Js6IaLWi0yGQvGr4JTAVV5EPMGz5es6pP7SMTJp25vEUKcpl/ce49bFmEdhcbKWkTlJInbJv5x21GSs4flxP+le/AUi70+sHAoukB1NOuYSFXQKBgGoGGDyA2VoqxuGrUaL8BdYgyz7WbXjCSCqAbnw3LeRgWjrhzmTR/7UNn4ryF0wBOE3MUkoVUFxRAwHSl0blbIW22lFyawx2iPP4wHc1YtPKI24UlmaI0r7ENB9epYeuWS2EgbNgRDnUi1LQtX+RKPRzbnRXYyM+a+TTmpC7ubPZAoGAbXFmd3s2ueK/zP04tHDXmXIohiyk0IjCALRRwrOA6qpSD8Zv2PHla41VGToSrSjggVDSJsX8dSMLAdYioABsow6Fhrbhj/eug6Xqhbm1tetIKxherpF2KvWMDbxQ+pd6pjfNI3JNn+cnA50bBrlKvaZSFGlz/3csCcJpXzk6XEUCgYEA5UTLS1U6gea4X7u73NTI9auoNACoyXBpLjvRLNQBPziOl2zHDGLaJXjDBcHeIYKe2+qe3svr+9fBzSOb1+zeoLtrrArPzGaSGpRi1gt4bL6tdBrjN0gtbCUwgA3zljSBl4UNNRVKAgHxyY/PU1/ZJM3e/p+SoW9n5Nwc+2S+nrQ=
  ali-pay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlgTohSGUsv6FbqlwGG1FRDe/bu9Uqai2+ZDwymIrXKSdD1VcXoywRjD2N9ymAf+C4cn3P/ymWBK4Ef4eYByt/9oUfeVf2kUCLoClbGu2hIgXGidWf5lqwUzSwg5/Vro7IuBRpKg6D/xV2wN1KPvM9DopjworPFeVaAUhPLFeDFk8jjXStT8SlznMeeLNmMFcnhpPrrwDxDUOH0AIYSECR0EGn/+QokUztVkEVa5MnrEsNta3Ss1cGYrK5mNUmjuYiZUwwao268nwuHaZqgyXX6up9IIMatlpSzvTuhTiAiqtbNN0BiodfN7tnNp820wJgsYsRksKlPeNKI3sQj6ZKQIDAQAB
  gateway-url: https://openapi.alipaydev.com/gateway.do
  notify-url: http://liuye.gz2vip.91tunnel.com/api/v1/pay/notify

ali-oss:
  end-point: oss-cn-beijing.aliyuncs.com
  bucket-name: onlinecinema
  key-id: LTAI5tLupzsqBxBewv2Wby2u
  key-secret: EM2WINdvqGFr2TZz0f1Q2M5zRZhn94

nginx:
  img-path: E:\nginx\html\imgs
  movie-preview-path: http://192.168.1.2:80/preivew
  movie-play-path: http://192.168.1.2:80/video